In [1]:
#Extração de dados Pokédex - Candidata Yasmin Couto

In [2]:
#Importando pacotes e requisitos para coleta
import requests
import pandas as pd

In [ ]:
##Espécies dos Pokemons

In [48]:
#Requisitando dados das especies e verificando status da resposta
especies = requests.get("https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0")
pokedex_especies = especies.json()

print("Status da requisição:",especies.status_code)
print("Chaves da requisição:",pokedex_especies.keys())

Status da requisição: 200
Chaves da requisição: dict_keys(['count', 'next', 'previous', 'results'])

In [4]:
#Criando dataframe base df_especies a partir da requisição e selecionando 151 especies de interesse

df_especies = pd.DataFrame.from_dict(pokedex_especies)
df_especies = df_especies['results']
df_especies = df_especies.apply(pd.Series)
df_especies = df_especies[:151]
df_especies = df_especies.rename(columns={'name': 'Pokemon'})

print(df_especies.shape)
df_especies.tail()

(151, 2)

       Pokemon                                     url
146    dratini  https://pokeapi.co/api/v2/pokemon/147/
147  dragonair  https://pokeapi.co/api/v2/pokemon/148/
148  dragonite  https://pokeapi.co/api/v2/pokemon/149/
149     mewtwo  https://pokeapi.co/api/v2/pokemon/150/
150        mew  https://pokeapi.co/api/v2/pokemon/151/

In [5]:
#Criando função para requisitar habilidades de cada espécie

def get_informacoes(i):
    r = requests.get(i)
    return r

In [6]:
#Criando loop para interar entre linhas do dataframe base df_especies
#Requisições serão armazenadas na lista req_informacoes

req_informacoes = []
for i in df_especies['url']:
  x = get_informacoes(i).json()
  req_informacoes.append(x)

In [7]:
#Criando o dataframe df que armazena as características de cada espécie
df = pd.DataFrame(req_informacoes)
df.head(1)

,abilities,base_experience,forms,game_indices,height,held_items,id,is_default,location_area_encounters,moves,name,order,past_types,species,sprites,stats,types,weight
0,"[{'ability': {'name': 'overgrow', 'url': 'http...",64,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'game_index': 153, 'version': {'name': 'red'...",7,[],1,True,https://pokeapi.co/api/v2/pokemon/1/encounters,"[{'move': {'name': 'razor-wind', 'url': 'https...",bulbasaur,1,[],"{'name': 'bulbasaur', 'url': 'https://pokeapi....",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 45, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'grass', 'url': ...",69

In [ ]:
##Forças dos Pokemons

In [8]:
#Estudando a documentação da API, stats representam as forças de cada pokemon:
  #stats(0)= HP
  #stats(1)= Ataque
  #stats(2)= Defesa
  #stats(3)= Ataque Especial 
  #stats(4)= Defesa Especial 
  #stats(5)= Velocidade

#Informações de stats coletadas ficam armazanadas no dataframe df_stats

df_stats = df['stats'].apply(pd.Series)
df_stats.head()

,0,1,2,3,4,5
0,"{'base_stat': 45, 'effort': 0, 'stat': {'name'...","{'base_stat': 49, 'effort': 0, 'stat': {'name'...","{'base_stat': 49, 'effort': 0, 'stat': {'name'...","{'base_stat': 65, 'effort': 1, 'stat': {'name'...","{'base_stat': 65, 'effort': 0, 'stat': {'name'...","{'base_stat': 45, 'effort': 0, 'stat': {'name'..."
1,"{'base_stat': 60, 'effort': 0, 'stat': {'name'...","{'base_stat': 62, 'effort': 0, 'stat': {'name'...","{'base_stat': 63, 'effort': 0, 'stat': {'name'...","{'base_stat': 80, 'effort': 1, 'stat': {'name'...","{'base_stat': 80, 'effort': 1, 'stat': {'name'...","{'base_stat': 60, 'effort': 0, 'stat': {'name'..."
2,"{'base_stat': 80, 'effort': 0, 'stat': {'name'...","{'base_stat': 82, 'effort': 0, 'stat': {'name'...","{'base_stat': 83, 'effort': 0, 'stat': {'name'...","{'base_stat': 100, 'effort': 2, 'stat': {'name...","{'base_stat': 100, 'effort': 1, 'stat': {'name...","{'base_stat': 80, 'effort': 0, 'stat': {'name'..."
3,"{'base_stat': 39, 'effort': 0, 'stat': {'name'...","{'base_stat': 52, 'effort': 0, 'stat': {'name'...","{'base_stat': 43, 'effort': 0, 'stat': {'name'...","{'base_stat': 60, 'effort': 0, 'stat': {'name'...","{'base_stat': 50, 'effort': 0, 'stat': {'name'...","{'base_stat': 65, 'effort': 1, 'stat': {'name'..."
4,"{'base_stat': 58, 'effort': 0, 'stat': {'name'...","{'base_stat': 64, 'effort': 0, 'stat': {'name'...","{'base_stat': 58, 'effort': 0, 'stat': {'name'...","{'base_stat': 80, 'effort': 1, 'stat': {'name'...","{'base_stat': 65, 'effort': 0, 'stat': {'name'...","{'base_stat': 80, 'effort': 1, 'stat': {'name'..."

In [9]:
#Extraindo o stats(0) e mesclando na dataframe base
df_hp=df_stats[0].apply(pd.Series)
df_hp=df_hp[['base_stat']]
df_hp = df_hp.rename(columns={'base_stat': 'HP'})

pokedex_temp1 = pd.merge(df_especies['Pokemon'], df_hp, left_index=True, right_index=True)
pokedex_temp1.head()

      Pokemon  HP
0   bulbasaur  45
1     ivysaur  60
2    venusaur  80
3  charmander  39
4  charmeleon  58

In [10]:
#Extraindo o stats(1) e mesclando na dataframe base
df_ataque=df_stats[1].apply(pd.Series)
df_ataque=df_ataque[['base_stat']]
df_ataque = df_ataque.rename(columns={'base_stat': 'Ataque'})

pokedex_temp2 = pd.merge(pokedex_temp1, df_ataque, left_index=True, right_index=True)
pokedex_temp2.head()

      Pokemon  HP  Ataque
0   bulbasaur  45      49
1     ivysaur  60      62
2    venusaur  80      82
3  charmander  39      52
4  charmeleon  58      64

In [11]:
#Extraindo o stats(2) e mesclando na dataframe base
df_defesa=df_stats[2].apply(pd.Series)
df_defesa=df_defesa[['base_stat']]
df_defesa = df_defesa.rename(columns={'base_stat': 'Defesa'})

pokedex_temp3 = pd.merge(pokedex_temp2, df_defesa, left_index=True, right_index=True)
pokedex_temp3.head(3)

     Pokemon  HP  Ataque  Defesa
0  bulbasaur  45      49      49
1    ivysaur  60      62      63
2   venusaur  80      82      83

In [12]:
#Extraindo o stats(3) e mesclando na dataframe base
df_ataque_especial=df_stats[3].apply(pd.Series)
df_ataque_especial=df_ataque_especial[['base_stat']]
df_ataque_especial = df_ataque_especial.rename(columns={'base_stat': 'Ataque Especial'})

pokedex_temp4 = pd.merge(pokedex_temp3, df_ataque_especial, left_index=True, right_index=True)
pokedex_temp4.head(3)

     Pokemon  HP  Ataque  Defesa  Ataque Especial
0  bulbasaur  45      49      49               65
1    ivysaur  60      62      63               80
2   venusaur  80      82      83              100

In [13]:
#Extraindo o stats(4) e mesclando na dataframe base
df_defesa_especial=df_stats[4].apply(pd.Series)
df_defesa_especial=df_defesa_especial[['base_stat']]
df_defesa_especial = df_defesa_especial.rename(columns={'base_stat': 'Defesa Especial'})

pokedex_temp5 = pd.merge(pokedex_temp4, df_defesa_especial, left_index=True, right_index=True)
pokedex_temp5.head(3)

     Pokemon  HP  Ataque  Defesa  Ataque Especial  Defesa Especial
0  bulbasaur  45      49      49               65               65
1    ivysaur  60      62      63               80               80
2   venusaur  80      82      83              100              100

In [14]:
#Extraindo o stats(5) e mesclando na dataframe base

df_velocidade=df_stats[5].apply(pd.Series)
df_velocidade=df_velocidade[['base_stat']]
df_velocidade = df_velocidade.rename(columns={'base_stat': 'Velocidade'})

pokedex_temp6 = pd.merge(pokedex_temp5, df_velocidade, left_index=True, right_index=True)
pokedex_temp6.head(3)

     Pokemon  HP  Ataque  Defesa  Ataque Especial  Defesa Especial  Velocidade
0  bulbasaur  45      49      49               65               65          45
1    ivysaur  60      62      63               80               80          60
2   venusaur  80      82      83              100              100          80

In [15]:
#Extraindo a altura e mesclando na dataframe base

df_altura = df[['height']]
df_altura = df_altura['height'].apply(pd.Series)
df_altura = df_altura.rename(columns={0: 'Altura'})


pokedex_temp7 = pd.merge(pokedex_temp6, df_altura, left_index=True, right_index=True)
pokedex_temp7.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura
0,bulbasaur,45,49,49,65,65,45,7
1,ivysaur,60,62,63,80,80,60,10
2,venusaur,80,82,83,100,100,80,20

In [16]:
#Extraindo o peso e mesclando na dataframe base

df_peso = df[['weight']]
df_peso = df_peso['weight'].apply(pd.Series)
df_peso = df_peso.rename(columns={0: 'Peso'})

pokedex_temp8 = pd.merge(pokedex_temp7, df_peso, left_index=True, right_index=True)
pokedex_temp8.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso
0,bulbasaur,45,49,49,65,65,45,7,69
1,ivysaur,60,62,63,80,80,60,10,130
2,venusaur,80,82,83,100,100,80,20,1000

In [ ]:
##Localização dos Pokemons

In [17]:
#Na requisição original temos um campo com urls de requisiçao de detalhes de "área de localização"
#As urls vão ser armazenadas no dataframe df_local
#É preciso criar um loop para interar entre linhas do dataframe df_local e coletar detalhes da localização
#Requisições serão armazenadas na lista req_local


df_local=df[['location_area_encounters']]

req_local = []
for i in df_local['location_area_encounters']:
  x = get_informacoes(i).json()
  req_local.append(x)

#OBS: somente os Pokemons originais tem localização, as evoluções não tem

In [18]:
#Informações de localização coletadas na requisição ficam armazanadas no dataframe df_localizacao
df_localizacao = pd.DataFrame(req_local)

In [19]:
#Extraindo a localização 1 e mesclando na dataframe base
temp_local1=df_localizacao[0].apply(pd.Series)

df_localizacao_1=temp_local1['location_area'].apply(pd.Series)
df_localizacao_1=df_localizacao_1[['name']]
df_localizacao_1 = df_localizacao_1.rename(columns={'name': 'Local 1'})

pokedex_temp9 = pd.merge(pokedex_temp8, df_localizacao_1, left_index=True, right_index=True)
pokedex_temp9.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area
1,ivysaur,60,62,63,80,80,60,10,130,NaN
2,venusaur,80,82,83,100,100,80,20,1000,NaN

In [20]:
#Extraindo a localização 1 e mesclando na dataframe base
temp_local2=df_localizacao[1].apply(pd.Series)

df_localizacao_2=temp_local2['location_area'].apply(pd.Series)
df_localizacao_2=df_localizacao_2[['name']]
df_localizacao_2 = df_localizacao_2.rename(columns={'name': 'Local 2'})

pokedex_temp10 = pd.merge(pokedex_temp9, df_localizacao_2, left_index=True, right_index=True)
pokedex_temp10.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN

In [ ]:
##Habilidades dos Pokemons

In [21]:
#Criando dataframe  df_habilidades para armazenar dados semi-tratados req_informacoes

df_habilidades = pd.DataFrame(req_informacoes)
df_habilidades = df_habilidades[['abilities']]
df_habilidades = df_habilidades['abilities'].apply(pd.Series)

df_habilidades.head(3)

,0,1,2
0,"{'ability': {'name': 'overgrow', 'url': 'https...","{'ability': {'name': 'chlorophyll', 'url': 'ht...",NaN
1,"{'ability': {'name': 'overgrow', 'url': 'https...","{'ability': {'name': 'chlorophyll', 'url': 'ht...",NaN
2,"{'ability': {'name': 'overgrow', 'url': 'https...","{'ability': {'name': 'chlorophyll', 'url': 'ht...",NaN

In [22]:
#Extraindo a habilidade 1 e mesclando na dataframe base

df_hab1=df_habilidades[0].apply(pd.Series)
df_hab1=df_hab1['ability'].apply(pd.Series)
df_hab1=df_hab1[['name']]
df_hab1 = df_hab1.rename(columns={'name': 'Habilidade 1'})

pokedex_temp11 = pd.merge(pokedex_temp10, df_hab1, left_index=True, right_index=True)
pokedex_temp11.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow

In [23]:
#Extraindo a habilidade 1 e mesclando na dataframe base

df_hab2=df_habilidades[1].apply(pd.Series)
df_hab2=df_hab2['ability'].apply(pd.Series)
df_hab2=df_hab2[['name']]
df_hab2 = df_hab2.rename(columns={'name': 'Habilidade 2'})

pokedex_temp12 = pd.merge(pokedex_temp11, df_hab2, left_index=True, right_index=True)
pokedex_temp12.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll

In [ ]:
##Movimentos dos Pokemons

In [24]:
#Cada pokemon tem vários movimentos possíveis, vamos extrair os 6 primeiros para montar a pokedex
#Informações de moves coletadas ficam armazanadas no dataframe df_moves

df_moves = df['moves'].apply(pd.Series)
df_moves.head()

,0,1,2,3,4,5,6,7,8,9,...,332,333,334,335,336,337,338,339,340,341
0,"{'move': {'name': 'razor-wind', 'url': 'https:...","{'move': {'name': 'swords-dance', 'url': 'http...","{'move': {'name': 'cut', 'url': 'https://pokea...","{'move': {'name': 'bind', 'url': 'https://poke...","{'move': {'name': 'vine-whip', 'url': 'https:/...","{'move': {'name': 'headbutt', 'url': 'https://...","{'move': {'name': 'tackle', 'url': 'https://po...","{'move': {'name': 'body-slam', 'url': 'https:/...","{'move': {'name': 'take-down', 'url': 'https:/...","{'move': {'name': 'double-edge', 'url': 'https...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'move': {'name': 'swords-dance', 'url': 'http...","{'move': {'name': 'cut', 'url': 'https://pokea...","{'move': {'name': 'bind', 'url': 'https://poke...","{'move': {'name': 'vine-whip', 'url': 'https:/...","{'move': {'name': 'headbutt', 'url': 'https://...","{'move': {'name': 'tackle', 'url': 'https://po...","{'move': {'name': 'body-slam', 'url': 'https:/...","{'move': {'name': 'take-down', 'url': 'https:/...","{'move': {'name': 'double-edge', 'url': 'https...","{'move': {'name': 'growl', 'url': 'https://pok...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'move': {'name': 'swords-dance', 'url': 'http...","{'move': {'name': 'cut', 'url': 'https://pokea...","{'move': {'name': 'bind', 'url': 'https://poke...","{'move': {'name': 'vine-whip', 'url': 'https:/...","{'move': {'name': 'headbutt', 'url': 'https://...","{'move': {'name': 'tackle', 'url': 'https://po...","{'move': {'name': 'body-slam', 'url': 'https:/...","{'move': {'name': 'take-down', 'url': 'https:/...","{'move': {'name': 'double-edge', 'url': 'https...","{'move': {'name': 'growl', 'url': 'https://pok...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'move': {'name': 'mega-punch', 'url': 'https:...","{'move': {'name': 'fire-punch', 'url': 'https:...","{'move': {'name': 'thunder-punch', 'url': 'htt...","{'move': {'name': 'scratch', 'url': 'https://p...","{'move': {'name': 'swords-dance', 'url': 'http...","{'move': {'name': 'cut', 'url': 'https://pokea...","{'move': {'name': 'wing-attack', 'url': 'https...","{'move': {'name': 'mega-kick', 'url': 'https:/...","{'move': {'name': 'headbutt', 'url': 'https://...","{'move': {'name': 'body-slam', 'url': 'https:/...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'move': {'name': 'mega-punch', 'url': 'https:...","{'move': {'name': 'fire-punch', 'url': 'https:...","{'move': {'name': 'thunder-punch', 'url': 'htt...","{'move': {'name': 'scratch', 'url': 'https://p...","{'move': {'name': 'swords-dance', 'url': 'http...","{'move': {'name': 'cut', 'url': 'https://pokea...","{'move': {'name': 'mega-kick', 'url': 'https:/...","{'move': {'name': 'headbutt', 'url': 'https://...","{'move': {'name': 'body-slam', 'url': 'https:/...","{'move': {'name': 'take-down', 'url': 'https:/...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#Extraindo o movimento 1 e mesclando na dataframe base

df_move1=df_moves[0].apply(pd.Series)
df_move1=df_move1['move'].apply(pd.Series)
df_move1=df_move1[['name']]
df_move1 = df_move1.rename(columns={'name': 'Movimento 1'})

pokedex_temp13 = pd.merge(pokedex_temp12, df_move1, left_index=True, right_index=True)
pokedex_temp13.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance

In [26]:
#Extraindo o movimento 2 e mesclando na dataframe base

df_move2=df_moves[1].apply(pd.Series)
df_move2=df_move2['move'].apply(pd.Series)
df_move2=df_move2[['name']]
df_move2 = df_move2.rename(columns={'name': 'Movimento 2'})

pokedex_temp14 = pd.merge(pokedex_temp13, df_move2, left_index=True, right_index=True)
pokedex_temp14.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut

In [27]:
#Extraindo o movimento 3 e mesclando na dataframe base

df_move3=df_moves[2].apply(pd.Series)
df_move3=df_move3['move'].apply(pd.Series)
df_move3=df_move3[['name']]
df_move3 = df_move3.rename(columns={'name': 'Movimento 3'})

pokedex_temp15 = pd.merge(pokedex_temp14, df_move3, left_index=True, right_index=True)
pokedex_temp15.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance,cut
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind

In [28]:
#Extraindo o movimento 4 e mesclando na dataframe base

df_move4=df_moves[3].apply(pd.Series)
df_move4=df_move4['move'].apply(pd.Series)
df_move4=df_move4[['name']]
df_move4 = df_move4.rename(columns={'name': 'Movimento 4'})

pokedex_temp16 = pd.merge(pokedex_temp15, df_move4, left_index=True, right_index=True)
pokedex_temp16.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance,cut,bind
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip

In [29]:
#Extraindo o movimento 5 e mesclando na dataframe base

df_move5=df_moves[4].apply(pd.Series)
df_move5=df_move5['move'].apply(pd.Series)
df_move5=df_move5[['name']]
df_move5 = df_move5.rename(columns={'name': 'Movimento 5'})

pokedex_temp17 = pd.merge(pokedex_temp16, df_move5, left_index=True, right_index=True)
pokedex_temp17.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4,Movimento 5
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance,cut,bind,vine-whip
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt

In [30]:
#Extraindo o movimento 6 e mesclando na dataframe base

df_move6=df_moves[5].apply(pd.Series)
df_move6=df_move6['move'].apply(pd.Series)
df_move6=df_move6[['name']]
df_move6 = df_move6.rename(columns={'name': 'Movimento 6'})

pokedex_temp18 = pd.merge(pokedex_temp17, df_move6, left_index=True, right_index=True)
pokedex_temp18.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4,Movimento 5,Movimento 6
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance,cut,bind,vine-whip,headbutt
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle

In [ ]:
##Imagens dos Pokemons

In [44]:
#Estudando a API, sei que em 'sprites' > 'front_shiny' armazena o link para a imagem png de cada pokemon
#Extraindo o link da image e mesclando na dataframe base para criar o arquivo final

df_imagem = df['sprites'].apply(pd.Series)
df_imagem=df_imagem[['front_shiny']]
df_imagem = df_imagem.rename(columns={'front_shiny': 'Imagem'})

pokedex_temp19 = pd.merge(pokedex_temp18, df_imagem, left_index=True, right_index=True)
pokedex_temp19.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,Local 2,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4,Movimento 5,Movimento 6,Imagem
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,pallet-town-area,overgrow,chlorophyll,razor-wind,swords-dance,cut,bind,vine-whip,headbutt,https://raw.githubusercontent.com/PokeAPI/spri...
1,ivysaur,60,62,63,80,80,60,10,130,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...
2,venusaur,80,82,83,100,100,80,20,1000,NaN,NaN,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...

In [39]:
df.head()

,abilities,base_experience,forms,game_indices,height,held_items,id,is_default,location_area_encounters,moves,name,order,past_types,species,sprites,stats,types,weight
0,"[{'ability': {'name': 'overgrow', 'url': 'http...",64,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'game_index': 153, 'version': {'name': 'red'...",7,[],1,True,https://pokeapi.co/api/v2/pokemon/1/encounters,"[{'move': {'name': 'razor-wind', 'url': 'https...",bulbasaur,1,[],"{'name': 'bulbasaur', 'url': 'https://pokeapi....",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 45, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'grass', 'url': ...",69
1,"[{'ability': {'name': 'overgrow', 'url': 'http...",142,"[{'name': 'ivysaur', 'url': 'https://pokeapi.c...","[{'game_index': 9, 'version': {'name': 'red', ...",10,[],2,True,https://pokeapi.co/api/v2/pokemon/2/encounters,"[{'move': {'name': 'swords-dance', 'url': 'htt...",ivysaur,2,[],"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 60, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'grass', 'url': ...",130
2,"[{'ability': {'name': 'overgrow', 'url': 'http...",263,"[{'name': 'venusaur', 'url': 'https://pokeapi....","[{'game_index': 154, 'version': {'name': 'red'...",20,[],3,True,https://pokeapi.co/api/v2/pokemon/3/encounters,"[{'move': {'name': 'swords-dance', 'url': 'htt...",venusaur,3,[],"{'name': 'venusaur', 'url': 'https://pokeapi.c...",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 80, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'grass', 'url': ...",1000
3,"[{'ability': {'name': 'blaze', 'url': 'https:/...",62,"[{'name': 'charmander', 'url': 'https://pokeap...","[{'game_index': 176, 'version': {'name': 'red'...",6,[],4,True,https://pokeapi.co/api/v2/pokemon/4/encounters,"[{'move': {'name': 'mega-punch', 'url': 'https...",charmander,5,[],"{'name': 'charmander', 'url': 'https://pokeapi...",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 39, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'fire', 'url': '...",85
4,"[{'ability': {'name': 'blaze', 'url': 'https:/...",142,"[{'name': 'charmeleon', 'url': 'https://pokeap...","[{'game_index': 178, 'version': {'name': 'red'...",11,[],5,True,https://pokeapi.co/api/v2/pokemon/5/encounters,"[{'move': {'name': 'mega-punch', 'url': 'https...",charmeleon,6,[],"{'name': 'charmeleon', 'url': 'https://pokeapi...",{'back_default': 'https://raw.githubuserconten...,"[{'base_stat': 58, 'effort': 0, 'stat': {'name...","[{'slot': 1, 'type': {'name': 'fire', 'url': '...",190

In [40]:
##Corrente Evolutiva dos Pokemons

In [41]:
#Criando loop para interar entre linhas do dataframe base df_especies
#Requisições serão armazenadas na lista req_informacoes

req_evolucao = []
for i in df['id']:
  link= "https://pokeapi.co/api/v2/pokemon-species/"+str(i)+"/"
  x = get_informacoes(link).json()
  req_evolucao.append(x)

In [42]:
#Criando o dataframe df_detalhes que armazena outras características de cada espécie
df_detalhes = pd.DataFrame(req_evolucao)
df_detalhes.head()

,base_happiness,capture_rate,color,egg_groups,evolution_chain,evolves_from_species,flavor_text_entries,form_descriptions,forms_switchable,gender_rate,...,is_baby,is_legendary,is_mythical,name,names,order,pal_park_encounters,pokedex_numbers,shape,varieties
0,50,45,"{'name': 'green', 'url': 'https://pokeapi.co/a...","[{'name': 'monster', 'url': 'https://pokeapi.c...",{'url': 'https://pokeapi.co/api/v2/evolution-c...,None,[{'flavor_text': 'A strange seed was planted o...,[],False,1,...,False,False,False,bulbasaur,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",1,"[{'area': {'name': 'field', 'url': 'https://po...","[{'entry_number': 1, 'pokedex': {'name': 'nati...","{'name': 'quadruped', 'url': 'https://pokeapi....","[{'is_default': True, 'pokemon': {'name': 'bul..."
1,50,45,"{'name': 'green', 'url': 'https://pokeapi.co/a...","[{'name': 'monster', 'url': 'https://pokeapi.c...",{'url': 'https://pokeapi.co/api/v2/evolution-c...,"{'name': 'bulbasaur', 'url': 'https://pokeapi....",[{'flavor_text': 'When the bulb on its back gr...,[],False,1,...,False,False,False,ivysaur,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",2,"[{'area': {'name': 'field', 'url': 'https://po...","[{'entry_number': 2, 'pokedex': {'name': 'nati...","{'name': 'quadruped', 'url': 'https://pokeapi....","[{'is_default': True, 'pokemon': {'name': 'ivy..."
2,50,45,"{'name': 'green', 'url': 'https://pokeapi.co/a...","[{'name': 'monster', 'url': 'https://pokeapi.c...",{'url': 'https://pokeapi.co/api/v2/evolution-c...,"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",[{'flavor_text': 'The plant blooms when it is ...,[],True,1,...,False,False,False,venusaur,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",3,"[{'area': {'name': 'field', 'url': 'https://po...","[{'entry_number': 3, 'pokedex': {'name': 'nati...","{'name': 'quadruped', 'url': 'https://pokeapi....","[{'is_default': True, 'pokemon': {'name': 'ven..."
3,50,45,"{'name': 'red', 'url': 'https://pokeapi.co/api...","[{'name': 'monster', 'url': 'https://pokeapi.c...",{'url': 'https://pokeapi.co/api/v2/evolution-c...,None,[{'flavor_text': 'Obviously prefers hot places...,[],False,1,...,False,False,False,charmander,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",4,"[{'area': {'name': 'field', 'url': 'https://po...","[{'entry_number': 4, 'pokedex': {'name': 'nati...","{'name': 'upright', 'url': 'https://pokeapi.co...","[{'is_default': True, 'pokemon': {'name': 'cha..."
4,50,45,"{'name': 'red', 'url': 'https://pokeapi.co/api...","[{'name': 'monster', 'url': 'https://pokeapi.c...",{'url': 'https://pokeapi.co/api/v2/evolution-c...,"{'name': 'charmander', 'url': 'https://pokeapi...",[{'flavor_text': 'When it swings its burning t...,[],False,1,...,False,False,False,charmeleon,"[{'language': {'name': 'ja-Hrkt', 'url': 'http...",5,"[{'area': {'name': 'field', 'url': 'https://po...","[{'entry_number': 5, 'pokedex': {'name': 'nati...","{'name': 'upright', 'url': 'https://pokeapi.co...","[{'is_default': True, 'pokemon': {'name': 'cha..."

In [45]:
#Extraindo o pokemon origem e mesclando na dataframe base
df_evolucao=df_detalhes['evolves_from_species'].apply(pd.Series)
df_evolucao = df_evolucao[['name']]
df_evolucao = df_evolucao.rename(columns={'name': 'Pokemon Origem'})

pokedex_temp20 = pd.merge(pokedex_temp19, df_evolucao, left_index=True, right_index=True)
pokedex_temp20.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,...,Habilidade 1,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4,Movimento 5,Movimento 6,Imagem,Pokemon Origem
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,...,overgrow,chlorophyll,razor-wind,swords-dance,cut,bind,vine-whip,headbutt,https://raw.githubusercontent.com/PokeAPI/spri...,NaN
1,ivysaur,60,62,63,80,80,60,10,130,NaN,...,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...,bulbasaur
2,venusaur,80,82,83,100,100,80,20,1000,NaN,...,overgrow,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...,ivysaur

In [46]:
#Extraindo a cor do pokemon e mesclando na dataframe base
df_cor =df_detalhes['color'].apply(pd.Series)
df_cor = df_cor[['name']]
df_cor = df_cor.rename(columns={'name': 'Cor'})

#Dataframe final
pokedex = pd.merge(pokedex_temp20, df_cor, left_index=True, right_index=True)
pokedex.head(3)

,Pokemon,HP,Ataque,Defesa,Ataque Especial,Defesa Especial,Velocidade,Altura,Peso,Local 1,...,Habilidade 2,Movimento 1,Movimento 2,Movimento 3,Movimento 4,Movimento 5,Movimento 6,Imagem,Pokemon Origem,Cor
0,bulbasaur,45,49,49,65,65,45,7,69,cerulean-city-area,...,chlorophyll,razor-wind,swords-dance,cut,bind,vine-whip,headbutt,https://raw.githubusercontent.com/PokeAPI/spri...,NaN,green
1,ivysaur,60,62,63,80,80,60,10,130,NaN,...,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...,bulbasaur,green
2,venusaur,80,82,83,100,100,80,20,1000,NaN,...,chlorophyll,swords-dance,cut,bind,vine-whip,headbutt,tackle,https://raw.githubusercontent.com/PokeAPI/spri...,ivysaur,green

In [47]:
#Salvando o dataframe final para formato CSV
pokedex.to_csv('pokedex.csv')